-- Corrección de posiciones para que coincidan con championshipplayers22.txt
-- Generado por scripts/fix-positions.mjs. Empareja por nombre.
begin;
update players set primary_position='MID' where full_name='Jamal Musiala' and primary_position='FWD';
update players set primary_position='FWD' where full_name='Jamie Leweling' and primary_position='MID';
update players set primary_position='DEF' where full_name='Joshua Kimmich' and primary_position='MID';
update players set primary_position='MID' where full_name='Nicolas Gonzalez' and primary_position='FWD';
update players set primary_position='MID' where full_name='Nicolas Paz' and primary_position='FWD';
update players set primary_position='MID' where full_name='Thiago Almada' and primary_position='FWD';
update players set primary_position='MID' where full_name='Alexander Prass' and primary_position='DEF';
update players set primary_position='DEF' where full_name='Konrad Laimer' and primary_position='MID';
update players set primary_position='FWD' where full_name='Patrick Wimmer' and primary_position='MID';
update players set primary_position='FWD' where full_name='Esmir Bajraktarevic' and primary_position='MID';
update players set primary_position='FWD' where full_name='Kerim Alajbegovic' and primary_position='MID';
update players set primary_position='FWD' where full_name='Jaminton Campaz' and primary_position='MID';
update players set primary_position='FWD' where full_name='Juan Fernando Quintero' and primary_position='MID';
update players set primary_position='FWD' where full_name='Hyun-jun Yang' and primary_position='MID';
update players set primary_position='FWD' where full_name='In-beom Hwang' and primary_position='MID';
update players set primary_position='MID' where full_name='Jens Castrop' and primary_position='DEF';
update players set primary_position='FWD' where full_name='Ji-sung Eom' and primary_position='MID';
update players set primary_position='MID' where full_name='Jin-seob Park' and primary_position='DEF';
update players set primary_position='MID' where full_name='Yu-min Cho' and primary_position='DEF';
update players set primary_position='MID' where full_name='Bazoumana Touré' and primary_position='FWD';
update players set primary_position='FWD' where full_name='Parfait Guiagon' and primary_position='MID';
update players set primary_position='MID' where full_name='Andrej Kramaric' and primary_position='FWD';
update players set primary_position='FWD' where full_name='Ar''Jany Martha' and primary_position='MID';
update players set primary_position='DEF' where full_name='Livano Comenencia' and primary_position='MID';
update players set primary_position='DEF' where full_name='Tyrese Noslin' and primary_position='MID';
update players set primary_position='FWD' where full_name='Ahmed Zizo' and primary_position='MID';
update players set primary_position='FWD' where full_name='Mahmoud Trezeguet' and primary_position='MID';
update players set primary_position='MID' where full_name='Brenden Aaronson' and primary_position='FWD';
update players set primary_position='MID' where full_name='Rayan Cherki' and primary_position='FWD';
update players set primary_position='FWD' where full_name='Daizen Maeda' and primary_position='MID';
update players set primary_position='FWD' where full_name='Koki Ogawa' and primary_position='MID';
update players set primary_position='FWD' where full_name='Ritsu Doan' and primary_position='MID';
update players set primary_position='FWD' where full_name='Takefusa Kubo' and primary_position='MID';
update players set primary_position='MID' where full_name='Callum McCowatt' and primary_position='FWD';
update players set primary_position='MID' where full_name='Lachlan Bayliss' and primary_position='FWD';
update players set primary_position='DEF' where full_name='Mats Wieffer' and primary_position='MID';
update players set primary_position='FWD' where full_name='Azarías Londoño' and primary_position='MID';
update players set primary_position='MID' where full_name='Francisco Trincão' and primary_position='FWD';
update players set primary_position='FWD' where full_name='Brian Cipenga' and primary_position='MID';
update players set primary_position='FWD' where full_name='Nathanael Mbuku' and primary_position='MID';
update players set primary_position='FWD' where full_name='Theo Bongonda' and primary_position='MID';
update players set primary_position='MID' where full_name='Iliman Ndiaye' and primary_position='FWD';
update players set primary_position='FWD' where full_name='Krépin Diatta' and primary_position='DEF';
update players set primary_position='MID' where full_name='Kamogelo Sebelebele' and primary_position='DEF';
update players set primary_position='MID' where full_name='Themba Zwane' and primary_position='FWD';
update players set primary_position='FWD' where full_name='Ismael Gharbi' and primary_position='MID';
update players set primary_position='FWD' where full_name='Mortadha Ben Ouanes' and primary_position='MID';
commit;
