-- =====================================================================
-- Draft Mundial 26 — Seed de plantillas CONFIRMADAS (generado)
-- Generado por scripts/generate-seed.mjs a partir del CSV de convocados.
-- 32 selecciones · 836 jugadores.
-- Idempotente (ON CONFLICT / NOT EXISTS).
-- =====================================================================

insert into public.national_teams (name, "group", flag_url) values
  ('Sudáfrica', 'A', 'https://flagcdn.com/w320/za.png'),
  ('Corea del Sur', 'A', 'https://flagcdn.com/w320/kr.png'),
  ('Bosnia y Herzegovina', 'B', 'https://flagcdn.com/w320/ba.png'),
  ('Suiza', 'B', 'https://flagcdn.com/w320/ch.png'),
  ('Brasil', 'C', 'https://flagcdn.com/w320/br.png'),
  ('Marruecos', 'C', 'https://flagcdn.com/w320/ma.png'),
  ('Haití', 'C', 'https://flagcdn.com/w320/ht.png'),
  ('Escocia', 'C', 'https://flagcdn.com/w320/gb-sct.png'),
  ('Estados Unidos', 'D', 'https://flagcdn.com/w320/us.png'),
  ('Alemania', 'E', 'https://flagcdn.com/w320/de.png'),
  ('Curazao', 'E', 'https://flagcdn.com/w320/cw.png'),
  ('Costa de Marfil', 'E', 'https://flagcdn.com/w320/ci.png'),
  ('Países Bajos', 'F', 'https://flagcdn.com/w320/nl.png'),
  ('Japón', 'F', 'https://flagcdn.com/w320/jp.png'),
  ('Suecia', 'F', 'https://flagcdn.com/w320/se.png'),
  ('Túnez', 'F', 'https://flagcdn.com/w320/tn.png'),
  ('Bélgica', 'G', 'https://flagcdn.com/w320/be.png'),
  ('Egipto', 'G', 'https://flagcdn.com/w320/eg.png'),
  ('Nueva Zelanda', 'G', 'https://flagcdn.com/w320/nz.png'),
  ('España', 'H', 'https://flagcdn.com/w320/es.png'),
  ('Cabo Verde', 'H', 'https://flagcdn.com/w320/cv.png'),
  ('Francia', 'I', 'https://flagcdn.com/w320/fr.png'),
  ('Senegal', 'I', 'https://flagcdn.com/w320/sn.png'),
  ('Noruega', 'I', 'https://flagcdn.com/w320/no.png'),
  ('Argentina', 'J', 'https://flagcdn.com/w320/ar.png'),
  ('Austria', 'J', 'https://flagcdn.com/w320/at.png'),
  ('Portugal', 'K', 'https://flagcdn.com/w320/pt.png'),
  ('República Democrática del Congo', 'K', 'https://flagcdn.com/w320/cd.png'),
  ('Colombia', 'K', 'https://flagcdn.com/w320/co.png'),
  ('Inglaterra', 'L', 'https://flagcdn.com/w320/gb-eng.png'),
  ('Croacia', 'L', 'https://flagcdn.com/w320/hr.png'),
  ('Panamá', 'L', 'https://flagcdn.com/w320/pa.png')
on conflict (name) do update set "group" = excluded."group", flag_url = excluded.flag_url;

insert into public.players (full_name, national_team_id, primary_position, club)
select v.full_name, t.id, v.pos::position_enum, nullif(v.club, '')
from (values
  ('Sipho Chaine', 'Sudáfrica', 'GK', 'Orlando Pirates'),
  ('Ricardo Goss', 'Sudáfrica', 'GK', 'Siwele'),
  ('Ronwen Williams', 'Sudáfrica', 'GK', 'Mamelodi Sundowns'),
  ('Aubrey Modiba', 'Sudáfrica', 'DEF', 'Mamelodi Sundowns'),
  ('Khuliso Mudau', 'Sudáfrica', 'DEF', 'Mamelodi Sundowns'),
  ('Nkosinathi Sibisi', 'Sudáfrica', 'DEF', 'Orlando Pirates'),
  ('Mbekezeli Mbokazi', 'Sudáfrica', 'DEF', 'Chicago Fire'),
  ('Ime Okon', 'Sudáfrica', 'DEF', 'Hannover'),
  ('Samukele Kabini', 'Sudáfrica', 'DEF', 'Molde'),
  ('Khulumani Ndamane', 'Sudáfrica', 'DEF', 'Mamelodi Sundowns'),
  ('Thabang Matuludi', 'Sudáfrica', 'DEF', 'Polokwane City'),
  ('Kamogelo Sebelebele', 'Sudáfrica', 'DEF', 'Orlando Pirates'),
  ('Bradley Cross', 'Sudáfrica', 'DEF', 'Kaizer Chiefs'),
  ('Olwethy Makhanya', 'Sudáfrica', 'DEF', 'Philadelphia Union'),
  ('Teboho Mokoena', 'Sudáfrica', 'MID', 'Mamelodi Sundowns'),
  ('Sphephelo Sithole', 'Sudáfrica', 'MID', 'Tondela'),
  ('Thalente Mbatha', 'Sudáfrica', 'MID', 'Orlando Pirates'),
  ('Jayden Adams', 'Sudáfrica', 'MID', 'Mamelodi Sundowns'),
  ('Themba Zwane', 'Sudáfrica', 'FWD', 'Mamelodi Sundowns'),
  ('Lyle Foster', 'Sudáfrica', 'FWD', 'Burnley'),
  ('Evidence Makgopa', 'Sudáfrica', 'FWD', 'Orlando Pirates'),
  ('Oswin Appollis', 'Sudáfrica', 'FWD', 'Orlando Pirates'),
  ('Iqraam Rayners', 'Sudáfrica', 'FWD', 'Mamelodi Sundowns'),
  ('Relebohile Mofokeng', 'Sudáfrica', 'FWD', 'Orlando Pirates'),
  ('Thapelo Maseko', 'Sudáfrica', 'FWD', 'AEL Limassol'),
  ('Tshepang Moremi', 'Sudáfrica', 'FWD', 'Orlando Pirates'),
  ('Hyeon-woo Jo', 'Corea del Sur', 'GK', 'Ulsan'),
  ('Seung-gyu Kim', 'Corea del Sur', 'GK', 'FC Tokyo'),
  ('Bum-keun Song', 'Corea del Sur', 'GK', 'Jeonbuk'),
  ('Moon-hwan Kim', 'Corea del Sur', 'DEF', 'Daejeon'),
  ('Min-jae Kim', 'Corea del Sur', 'DEF', 'Bayern Munich'),
  ('Tae-hyon Kim', 'Corea del Sur', 'DEF', 'Kashima Antlers'),
  ('Jin-seob Park', 'Corea del Sur', 'DEF', 'Zhejiang'),
  ('Young-woo Sool', 'Corea del Sur', 'DEF', 'Red Star Belgrade'),
  ('Jens Castrop', 'Corea del Sur', 'DEF', 'Borussia Monchengladbach'),
  ('Ki-hyuk Lee', 'Corea del Sur', 'DEF', 'Gangwon'),
  ('Tae-seok Lee', 'Corea del Sur', 'DEF', 'Austria Wien'),
  ('Han-beom Lee', 'Corea del Sur', 'DEF', 'Midtjylland'),
  ('Yu-min Cho', 'Corea del Sur', 'DEF', 'Sharjah'),
  ('Jin-gyu Kim', 'Corea del Sur', 'MID', 'Jeonbuk'),
  ('Jun-ho Bae', 'Corea del Sur', 'MID', 'Stoke City'),
  ('Seung-ho Paik', 'Corea del Sur', 'MID', 'Birmingham'),
  ('Hyun-jun Yang', 'Corea del Sur', 'MID', 'Celtic'),
  ('Ji-sung Eom', 'Corea del Sur', 'MID', 'Swansea'),
  ('Kang-in Lee', 'Corea del Sur', 'MID', 'Paris St-Germain'),
  ('Dong-gyeong Lee', 'Corea del Sur', 'MID', 'Ulsan'),
  ('Jae-sung Lee', 'Corea del Sur', 'MID', 'Mainz'),
  ('In-beom Hwang', 'Corea del Sur', 'MID', 'Feyenoord'),
  ('Hee-chan Hwang', 'Corea del Sur', 'MID', 'Wolves'),
  ('Heung-min Son', 'Corea del Sur', 'FWD', 'LAFC'),
  ('Hyeon-gyu Oh', 'Corea del Sur', 'FWD', 'Besitkas'),
  ('Gue-sung Cho', 'Corea del Sur', 'FWD', 'Midtjylland'),
  ('Nikola Vasilj', 'Bosnia y Herzegovina', 'GK', 'St Pauli'),
  ('Martin Zlomislic', 'Bosnia y Herzegovina', 'GK', 'Rijeka'),
  ('Osman Hadzikic', 'Bosnia y Herzegovina', 'GK', 'Slaven Belupo'),
  ('Sead Kolasinac', 'Bosnia y Herzegovina', 'DEF', 'Atalanta'),
  ('Amar Dedic', 'Bosnia y Herzegovina', 'DEF', 'Benfica'),
  ('Nihad Mujakic', 'Bosnia y Herzegovina', 'DEF', 'Gaziantep'),
  ('Nikola Katic', 'Bosnia y Herzegovina', 'DEF', 'Schalke 04'),
  ('Tarik Muharemovic', 'Bosnia y Herzegovina', 'DEF', 'Sassuolo'),
  ('Stjepan Radeljic', 'Bosnia y Herzegovina', 'DEF', 'Rijeka'),
  ('Dennis Hadzikadunic', 'Bosnia y Herzegovina', 'DEF', 'Sampdoria'),
  ('Nidal Celik', 'Bosnia y Herzegovina', 'DEF', 'Lens'),
  ('Amir Hadziahmetovic', 'Bosnia y Herzegovina', 'MID', 'Hull City'),
  ('Ivan Sunjic', 'Bosnia y Herzegovina', 'MID', 'Pafos'),
  ('Ivan Basic', 'Bosnia y Herzegovina', 'MID', 'Astana'),
  ('Dzenis Burnic', 'Bosnia y Herzegovina', 'MID', 'Karlsruher SC'),
  ('Ermin Mahmic', 'Bosnia y Herzegovina', 'MID', 'Slovan Liberec'),
  ('Benjamin Tahirovic', 'Bosnia y Herzegovina', 'MID', 'Brondby'),
  ('Amar Memic', 'Bosnia y Herzegovina', 'MID', 'Viktoria Plzen'),
  ('Armin Gigovic', 'Bosnia y Herzegovina', 'MID', 'Young Boys'),
  ('Kerim Alajbegovic', 'Bosnia y Herzegovina', 'MID', 'RB Salzburg'),
  ('Esmir Bajraktarevic', 'Bosnia y Herzegovina', 'MID', 'PSV Eindhoven'),
  ('Ermedin Demirovic', 'Bosnia y Herzegovina', 'FWD', 'VfB Stuttgart'),
  ('Jovo Lukic', 'Bosnia y Herzegovina', 'FWD', 'Universitatea Cluj'),
  ('Samed Bazdar', 'Bosnia y Herzegovina', 'FWD', 'Jagiellonia Bialystok'),
  ('Haris Tabakovic', 'Bosnia y Herzegovina', 'FWD', 'Borussia Moenchengladbach'),
  ('Edin Dzeko', 'Bosnia y Herzegovina', 'FWD', 'Schalke 04'),
  ('Marvin Keller', 'Suiza', 'GK', 'Young Boys'),
  ('Gregor Kobel', 'Suiza', 'GK', 'Borussia Dortmund'),
  ('Yvon Mvogo', 'Suiza', 'GK', 'Lorient'),
  ('Manuel Akanji', 'Suiza', 'DEF', 'Inter Milan'),
  ('Aurele Amenda', 'Suiza', 'DEF', 'Eintracht Frankfurt'),
  ('Eray Comert', 'Suiza', 'DEF', 'Valencia'),
  ('Nico Elvedi', 'Suiza', 'DEF', 'Borussia Monchengladbach'),
  ('Luca Jaquez', 'Suiza', 'DEF', 'VfB Stuttgart'),
  ('Miro Muheim', 'Suiza', 'DEF', 'Hamburg'),
  ('Ricardo Rodriguez', 'Suiza', 'DEF', 'Real Betis'),
  ('Silvan Widmer', 'Suiza', 'DEF', 'Mainz'),
  ('Michel Aebischer', 'Suiza', 'MID', 'Pisa'),
  ('Christian Fassnacht', 'Suiza', 'MID', 'Young Boys'),
  ('Remo Freuler', 'Suiza', 'MID', 'Bologna'),
  ('Ardon Jashari', 'Suiza', 'MID', 'AC Milan'),
  ('Johan Manzambi', 'Suiza', 'MID', 'Freiburg'),
  ('Fabian Rieder', 'Suiza', 'MID', 'Augsburg'),
  ('Djibril Sow', 'Suiza', 'MID', 'Sevilla'),
  ('Ruben Vargas', 'Suiza', 'MID', 'Sevilla'),
  ('Granit Xhaka', 'Suiza', 'MID', 'Sunderland'),
  ('Denis Zakaria', 'Suiza', 'MID', 'Monaco'),
  ('Zeki Amdouni', 'Suiza', 'FWD', 'Burnley'),
  ('Breel Embolo', 'Suiza', 'FWD', 'Stade Rennais'),
  ('Cedric Itten', 'Suiza', 'FWD', 'Fortuna Dusseldorf'),
  ('Dan Ndoye', 'Suiza', 'FWD', 'Nottingham Forest'),
  ('Noah Okafor', 'Suiza', 'FWD', 'Leeds'),
  ('Alisson', 'Brasil', 'GK', 'Liverpool'),
  ('Ederson', 'Brasil', 'GK', 'Fenerbahce'),
  ('Weverton', 'Brasil', 'GK', 'Gremio'),
  ('Marquinhos', 'Brasil', 'DEF', 'PSG'),
  ('Gabriel', 'Brasil', 'DEF', 'Arsenal'),
  ('Bremer', 'Brasil', 'DEF', 'Juventus'),
  ('Ibanez', 'Brasil', 'DEF', 'Al Ahli'),
  ('Leo Pereira', 'Brasil', 'DEF', 'Flamengo'),
  ('Wesley', 'Brasil', 'DEF', 'Roma'),
  ('Danilo', 'Brasil', 'DEF', 'Flamengo'),
  ('Alex Sandro', 'Brasil', 'DEF', 'Flamengo'),
  ('Douglas Santos', 'Brasil', 'DEF', 'Zenit'),
  ('Casemiro', 'Brasil', 'MID', 'Manchester United'),
  ('Bruno Guimaraes', 'Brasil', 'MID', 'Newcastle'),
  ('Fabinho', 'Brasil', 'MID', 'Al Ittihad'),
  ('Danilo', 'Brasil', 'MID', 'Botafogo'),
  ('Lucas Paqueta', 'Brasil', 'MID', 'Flamengo'),
  ('Vinicius Jr', 'Brasil', 'FWD', 'Real Madrid'),
  ('Raphinha', 'Brasil', 'FWD', 'Barcelona'),
  ('Matheus Cunha', 'Brasil', 'FWD', 'Manchester United'),
  ('Luiz Henrique', 'Brasil', 'FWD', 'Zenit'),
  ('Igor Thiago', 'Brasil', 'FWD', 'Brentford'),
  ('Endrick', 'Brasil', 'FWD', 'Lyon/Real Madrid'),
  ('Martinelli', 'Brasil', 'FWD', 'Arsenal'),
  ('Rayan', 'Brasil', 'FWD', 'Bournemouth'),
  ('Neymar', 'Brasil', 'FWD', 'Santos'),
  ('Yassine Bounou', 'Marruecos', 'GK', 'Al Hilal'),
  ('Munir Mohamedi', 'Marruecos', 'GK', 'RS Berkane'),
  ('Ahmed Tagnaouti', 'Marruecos', 'GK', 'Royal Armed Forces'),
  ('Noussair Mazraoui', 'Marruecos', 'DEF', 'Manchester United'),
  ('Anass Salah-Eddine', 'Marruecos', 'DEF', 'PSV Eindhoven'),
  ('Youssef Belammari', 'Marruecos', 'DEF', 'Al Ahly'),
  ('Nayef Aguerd', 'Marruecos', 'DEF', 'Marseille'),
  ('Chadi Riad', 'Marruecos', 'DEF', 'Crystal Palace'),
  ('Issa Diop', 'Marruecos', 'DEF', 'West Ham United'),
  ('Redouane Halhal', 'Marruecos', 'DEF', 'KV Mechelen'),
  ('Achraf Hakimi', 'Marruecos', 'DEF', 'Paris St-Germain'),
  ('Zakaria El Ouahdi', 'Marruecos', 'DEF', 'Genk'),
  ('Samir El Mourabet', 'Marruecos', 'MID', 'Strasbourg'),
  ('Ayyoub Bouaddi', 'Marruecos', 'MID', 'Lille'),
  ('Neil El Aynaoui', 'Marruecos', 'MID', 'Roma'),
  ('Sofyan Amrabat', 'Marruecos', 'MID', 'Real Betis'),
  ('Azzedine Ounahi', 'Marruecos', 'MID', 'Girona'),
  ('Bilal El Khannouss', 'Marruecos', 'MID', 'Stuttgart'),
  ('Ismael Saibari', 'Marruecos', 'MID', 'PSV Eindhoven'),
  ('Abdessamad Ezzalzouli', 'Marruecos', 'FWD', 'Real Betis'),
  ('Chemsdine Talbi', 'Marruecos', 'FWD', 'Sunderland'),
  ('Soufiane Rahimi', 'Marruecos', 'FWD', 'Al Ain'),
  ('Ayoub El Kaabi', 'Marruecos', 'FWD', 'Olympiacos'),
  ('Brahim Diaz', 'Marruecos', 'FWD', 'Real Madrid'),
  ('Yassine Gessime', 'Marruecos', 'FWD', 'Strasbourg'),
  ('Ayoub Amaimouni-Echghouyabe', 'Marruecos', 'FWD', 'Eintracht Frankfurt'),
  ('Johnny Placide', 'Haití', 'GK', 'Bastia'),
  ('Alexandre Pierre', 'Haití', 'GK', 'Sochaux'),
  ('Josue Duverger', 'Haití', 'GK', 'FC Cosmos Koblenz'),
  ('Carlens Arcus', 'Haití', 'DEF', 'Angers'),
  ('Wilguens Pauguain', 'Haití', 'DEF', 'Zulte Waregem'),
  ('Duke Lacroix', 'Haití', 'DEF', 'Colorado Springs'),
  ('Martin Expérience', 'Haití', 'DEF', 'Nancy'),
  ('Jean-Kevin Duverne', 'Haití', 'DEF', 'KAA Gent'),
  ('Ricardo Ade', 'Haití', 'DEF', 'LDU Quito'),
  ('Hannes Delcroix', 'Haití', 'DEF', 'Lugano'),
  ('Keeto Thermoncy', 'Haití', 'DEF', 'Young Boys Berne'),
  ('Leverton Pierre', 'Haití', 'MID', 'Vizela'),
  ('Carl-Fred Sainthe', 'Haití', 'MID', 'El Paso Locomotive'),
  ('Jean-Jacques Danley', 'Haití', 'MID', 'Philadelphia Union'),
  ('Jean-Ricner Bellegarde', 'Haití', 'MID', 'Wolves'),
  ('Pierre Woodenski', 'Haití', 'MID', 'Violette'),
  ('Dominique Simon', 'Haití', 'MID', 'Tatran Presov'),
  ('Louicius Deedson', 'Haití', 'FWD', 'Dallas'),
  ('Ruben Providence', 'Haití', 'FWD', 'Almere City'),
  ('Josue Casimir', 'Haití', 'FWD', 'Auxerre'),
  ('Derrick Etienne', 'Haití', 'FWD', 'Toronto'),
  ('Wilson Isidor', 'Haití', 'FWD', 'Sunderland'),
  ('Duckens Nazon', 'Haití', 'FWD', 'Esteghlal'),
  ('Frantzdy Pierrot', 'Haití', 'FWD', 'Caykur Rizespor'),
  ('Yassin Fortune', 'Haití', 'FWD', 'Vizela'),
  ('Lenny Joseph', 'Haití', 'FWD', 'Ferencvaros'),
  ('Craig Gordon', 'Escocia', 'GK', 'Hearts'),
  ('Angus Gunn', 'Escocia', 'GK', 'Nottingham Forest'),
  ('Liam Kelly', 'Escocia', 'GK', 'Rangers'),
  ('Grant Hanley', 'Escocia', 'DEF', 'Hibernian'),
  ('Jack Hendry', 'Escocia', 'DEF', 'Al Etiffaq'),
  ('Aaron Hickey', 'Escocia', 'DEF', 'Brentford'),
  ('Dom Hyam', 'Escocia', 'DEF', 'Wrexham'),
  ('Scott McKenna', 'Escocia', 'DEF', 'Dinamo Zagreb'),
  ('Nathan Patterson', 'Escocia', 'DEF', 'Everton'),
  ('Anthony Ralston', 'Escocia', 'DEF', 'Celtic'),
  ('Andy Robertson', 'Escocia', 'DEF', 'Liverpool'),
  ('John Souttar', 'Escocia', 'DEF', 'Rangers'),
  ('Kieran Tierney', 'Escocia', 'DEF', 'Celtic'),
  ('Ryan Christie', 'Escocia', 'MID', 'Bournemouth'),
  ('Findlay Curtis', 'Escocia', 'MID', 'Kilmarnock'),
  ('Lewis Ferguson', 'Escocia', 'MID', 'Bologna'),
  ('Ben Gannon-Doak', 'Escocia', 'MID', 'Bournemouth'),
  ('Billy Gilmour', 'Escocia', 'MID', 'Napoli'),
  ('John McGinn', 'Escocia', 'MID', 'Aston Villa'),
  ('Kenny McLean', 'Escocia', 'MID', 'Norwich'),
  ('Scott McTominay', 'Escocia', 'MID', 'Napoli'),
  ('Che Adams', 'Escocia', 'FWD', 'Torino'),
  ('Lyndon Dykes', 'Escocia', 'FWD', 'Charlton Athletic'),
  ('George Hirst', 'Escocia', 'FWD', 'Ipswich'),
  ('Lawrence Shankland', 'Escocia', 'FWD', 'Hearts'),
  ('Ross Stewart', 'Escocia', 'FWD', 'Southampton'),
  ('Chris Brady', 'Estados Unidos', 'GK', 'Chicago Fire'),
  ('Matt Freese', 'Estados Unidos', 'GK', 'New York City FC'),
  ('Matt Turner', 'Estados Unidos', 'GK', 'New England Revolution'),
  ('Max Arfsten', 'Estados Unidos', 'DEF', 'Columbus Crew'),
  ('Sergiño Dest', 'Estados Unidos', 'DEF', 'PSV Eindhoven'),
  ('Alex Freeman', 'Estados Unidos', 'DEF', 'Villarreal'),
  ('Mark McKenzie', 'Estados Unidos', 'DEF', 'Toulouse'),
  ('Tim Ream', 'Estados Unidos', 'DEF', 'Charlotte FC'),
  ('Chris Richards', 'Estados Unidos', 'DEF', 'Crystal Palace'),
  ('Antonee Robinson', 'Estados Unidos', 'DEF', 'Fulham'),
  ('Miles Robinson', 'Estados Unidos', 'DEF', 'FC Cincinnati'),
  ('Joe Scally', 'Estados Unidos', 'DEF', 'Borussia Mönchengladbach'),
  ('Auston Trusty', 'Estados Unidos', 'DEF', 'Celtic'),
  ('Tyler Adams', 'Estados Unidos', 'MID', 'AFC Bournemouth'),
  ('Sebastian Berhalter', 'Estados Unidos', 'MID', 'Vancouver Whitecaps'),
  ('Weston McKennie', 'Estados Unidos', 'MID', 'Juventus'),
  ('Gio Reyna', 'Estados Unidos', 'MID', 'Borussia Mönchengladbach'),
  ('Cristian Roldan', 'Estados Unidos', 'MID', 'Seattle Sounders'),
  ('Malik Tillman', 'Estados Unidos', 'MID', 'Bayer Leverkusen'),
  ('Brenden Aaronson', 'Estados Unidos', 'FWD', 'Leeds United'),
  ('Folarin Balogun', 'Estados Unidos', 'FWD', 'Monaco'),
  ('Ricardo Pepi', 'Estados Unidos', 'FWD', 'PSV Eindhoven'),
  ('Christian Pulisic', 'Estados Unidos', 'FWD', 'AC Milan'),
  ('Tim Weah', 'Estados Unidos', 'FWD', 'Marseille'),
  ('Haji Wright', 'Estados Unidos', 'FWD', 'Coventry City'),
  ('Alejandro Zendejas', 'Estados Unidos', 'FWD', 'Club América'),
  ('Oliver Baumann', 'Alemania', 'GK', 'Hoffenheim'),
  ('Manuel Neuer', 'Alemania', 'GK', 'Bayern Munich'),
  ('Alexander Nubel', 'Alemania', 'GK', 'Stuttgart'),
  ('Waldemar Anton', 'Alemania', 'DEF', 'Borussia Dortmund'),
  ('Nathaniel Brown', 'Alemania', 'DEF', 'Eintracht Frankfurt'),
  ('David Raum', 'Alemania', 'DEF', 'RB Leipzig'),
  ('Antonio Rudiger', 'Alemania', 'DEF', 'Real Madrid'),
  ('Nico Schlotterbeck', 'Alemania', 'DEF', 'Borussia Dortmund'),
  ('Jonathan Tah', 'Alemania', 'DEF', 'Bayern Munich'),
  ('Malick Thiaw', 'Alemania', 'DEF', 'Newcastle United'),
  ('Nadiem Amiri', 'Alemania', 'MID', 'Mainz'),
  ('Leon Goretzka', 'Alemania', 'MID', 'Bayern Munich'),
  ('Pascal Gross', 'Alemania', 'MID', 'Brighton and Hove Albion'),
  ('Joshua Kimmich', 'Alemania', 'MID', 'Bayern Munich'),
  ('Jamie Leweling', 'Alemania', 'MID', 'Stuttgart'),
  ('Felix Nmecha', 'Alemania', 'MID', 'Borussia Dortmund'),
  ('Aleksandar Pavlovic', 'Alemania', 'MID', 'Bayern Munich'),
  ('Angelo Stiller', 'Alemania', 'MID', 'Stuttgart'),
  ('Florian Wirtz', 'Alemania', 'MID', 'Liverpool'),
  ('Maximilian Beier', 'Alemania', 'FWD', 'Borussia Dortmund'),
  ('Kai Havertz', 'Alemania', 'FWD', 'Arsenal'),
  ('Lennart Karl', 'Alemania', 'FWD', 'Bayern Munich'),
  ('Jamal Musiala', 'Alemania', 'FWD', 'Bayern Munich'),
  ('Leroy Sane', 'Alemania', 'FWD', 'Galatasaray'),
  ('Deniz Undav', 'Alemania', 'FWD', 'Stuttgart'),
  ('Nick Woltemade', 'Alemania', 'FWD', 'Newcastle United'),
  ('Tyrick Bodak', 'Curazao', 'GK', 'SC Telstar'),
  ('Trevor Doornbusch', 'Curazao', 'GK', 'VVV-Venlo'),
  ('Eloy Room', 'Curazao', 'GK', 'Miami FC'),
  ('Riechedly Bazoer', 'Curazao', 'DEF', 'Konyaspor'),
  ('Joshua Brenet', 'Curazao', 'DEF', 'Kayserispor'),
  ('Roshon Van Eijma', 'Curazao', 'DEF', 'RKC Waalwijk'),
  ('Sherel Floranus', 'Curazao', 'DEF', 'PEC Zwolle'),
  ('Deveron Fonville', 'Curazao', 'DEF', 'NEC Nijmegen'),
  ('Jurien Gaari', 'Curazao', 'DEF', 'Abha Club'),
  ('Armando Obispo', 'Curazao', 'DEF', 'PSV Eindhoven'),
  ('Shurandy Sambo', 'Curazao', 'DEF', 'Sparta Rotterdam'),
  ('Juninho Bacuna', 'Curazao', 'MID', 'FC Volendam'),
  ('Leandro Bacuna', 'Curazao', 'MID', 'Igdır'),
  ('Livano Comenencia', 'Curazao', 'MID', 'FC Zürich'),
  ('Kevin Felida', 'Curazao', 'MID', 'FC Den Bosch'),
  ('Ar''Jany Martha', 'Curazao', 'MID', 'Rotherham'),
  ('Tyrese Noslin', 'Curazao', 'MID', 'SC Telstar'),
  ('Godfried Roemeratoe', 'Curazao', 'MID', 'RKC Waalwijk'),
  ('Jeremy Antonisse', 'Curazao', 'FWD', 'AE Kifisia'),
  ('Tahith Chong', 'Curazao', 'FWD', 'Sheffield United'),
  ('Kenji Gorré', 'Curazao', 'FWD', 'Maccabi Haifa'),
  ('Sontje Hansen', 'Curazao', 'FWD', 'Middlesbrough'),
  ('Gervane Kastaneer', 'Curazao', 'FWD', 'Terengganu FC'),
  ('Brandley Kuwas', 'Curazao', 'FWD', 'FC Volendam'),
  ('Jürgen Locadia', 'Curazao', 'FWD', 'Miami FC'),
  ('Jearl Margaritha', 'Curazao', 'FWD', 'SK Beveren'),
  ('Yahia Fofana', 'Costa de Marfil', 'GK', 'Çaykur Rizespor'),
  ('Mohamed Koné', 'Costa de Marfil', 'GK', 'Charleroi'),
  ('Alban Lafont', 'Costa de Marfil', 'GK', 'Panathinaikos'),
  ('Emmanuel Agbadou', 'Costa de Marfil', 'DEF', 'Beşiktaş'),
  ('Clément Akpa', 'Costa de Marfil', 'DEF', 'AJ Auxerre'),
  ('Ousmane Diomande', 'Costa de Marfil', 'DEF', 'Sporting'),
  ('Guela Doué', 'Costa de Marfil', 'DEF', 'Strasbourg'),
  ('Ghislain Konan', 'Costa de Marfil', 'DEF', 'Gil Vicente'),
  ('Odilon Kossounou', 'Costa de Marfil', 'DEF', 'Atalanta BC'),
  ('Evan Ndicka', 'Costa de Marfil', 'DEF', 'Roma'),
  ('Wilfried Singo', 'Costa de Marfil', 'DEF', 'Galatasaray'),
  ('Seko Fofana', 'Costa de Marfil', 'MID', 'Porto'),
  ('Parfait Guiagon', 'Costa de Marfil', 'MID', 'Charleroi'),
  ('Christ Inao Oulaï', 'Costa de Marfil', 'MID', 'Trabzonspor'),
  ('Franck Kessié', 'Costa de Marfil', 'MID', 'Al Ahli'),
  ('Ibrahim Sangaré', 'Costa de Marfil', 'MID', 'Nottingham Forest'),
  ('Jean-Michaël Seri', 'Costa de Marfil', 'MID', 'Maribor'),
  ('Simon Adingra', 'Costa de Marfil', 'FWD', 'Monaco'),
  ('Ange-Yoan Bonny', 'Costa de Marfil', 'FWD', 'Inter Milan'),
  ('Amad Diallo', 'Costa de Marfil', 'FWD', 'Manchester United'),
  ('Oumar Diakité', 'Costa de Marfil', 'FWD', 'Cercle Brugge'),
  ('Yan Diomande', 'Costa de Marfil', 'FWD', 'RB Leipzig'),
  ('Evann Guessand', 'Costa de Marfil', 'FWD', 'Crystal Palace'),
  ('Nicolas Pépé', 'Costa de Marfil', 'FWD', 'Villarreal'),
  ('Bazoumana Touré', 'Costa de Marfil', 'FWD', 'Hoffenheim'),
  ('Elye Wahi', 'Costa de Marfil', 'FWD', 'Nice'),
  ('Mark Flekken', 'Países Bajos', 'GK', 'Bayer Leverkusen'),
  ('Robin Roefs', 'Países Bajos', 'GK', 'Sunderland'),
  ('Bart Verbruggen', 'Países Bajos', 'GK', 'Brighton'),
  ('Nathan Aké', 'Países Bajos', 'DEF', 'Manchester City'),
  ('Virgil van Dijk', 'Países Bajos', 'DEF', 'Liverpool'),
  ('Denzel Dumfries', 'Países Bajos', 'DEF', 'Inter Milan'),
  ('Jorrel Hato', 'Países Bajos', 'DEF', 'Chelsea'),
  ('Jan Paul van Hecke', 'Países Bajos', 'DEF', 'Brighton'),
  ('Micky van de Ven', 'Países Bajos', 'DEF', 'Tottenham'),
  ('Jurrien Timber', 'Países Bajos', 'DEF', 'Arsenal'),
  ('Ryan Gravenberch', 'Países Bajos', 'MID', 'Liverpool'),
  ('Frenkie de Jong', 'Países Bajos', 'MID', 'Barcelona'),
  ('Teun Koopmeiners', 'Países Bajos', 'MID', 'Juventus'),
  ('Tijjani Reijnders', 'Países Bajos', 'MID', 'Manchester City'),
  ('Marten de Roon', 'Países Bajos', 'MID', 'Atalanta'),
  ('Guus Til', 'Países Bajos', 'MID', 'PSV Eindhoven'),
  ('Quinten Timber', 'Países Bajos', 'MID', 'Marseille'),
  ('Mats Wieffer', 'Países Bajos', 'MID', 'Brighton'),
  ('Brian Brobbey', 'Países Bajos', 'FWD', 'Sunderland'),
  ('Memphis Depay', 'Países Bajos', 'FWD', 'Corinthians'),
  ('Cody Gakpo', 'Países Bajos', 'FWD', 'Liverpool'),
  ('Justin Kluivert', 'Países Bajos', 'FWD', 'Bournemouth'),
  ('Noa Lang', 'Países Bajos', 'FWD', 'Galatasaray'),
  ('Donyell Malen', 'Países Bajos', 'FWD', 'Roma'),
  ('Crysencio Summerville', 'Países Bajos', 'FWD', 'West Ham'),
  ('Wout Weghorst', 'Países Bajos', 'FWD', 'Ajax'),
  ('Tomoki Hayakawa', 'Japón', 'GK', 'Kashima Antlers'),
  ('Keisuke Osako', 'Japón', 'GK', 'Sanfrecce Hiroshima'),
  ('Aya Suzuka', 'Japón', 'GK', 'Parma Calcio'),
  ('Yuto Nagatomo', 'Japón', 'DEF', 'FC Tokyo'),
  ('Shogo Taniguchi', 'Japón', 'DEF', 'Sint-Truiden'),
  ('Ko Itakura', 'Japón', 'DEF', 'Ajax'),
  ('Tsuyoshi Watanabe', 'Japón', 'DEF', 'Feyenoord'),
  ('Takehiro Tomiyasu', 'Japón', 'DEF', 'Ajax'),
  ('Hiroki Ito', 'Japón', 'DEF', 'Bayern Munich'),
  ('Ayumu Seko', 'Japón', 'DEF', 'Le Havre AC'),
  ('Yukinari Sugawara', 'Japón', 'DEF', 'Werder Bremen'),
  ('Junosuke Suzuki', 'Japón', 'DEF', 'FC Copenhagen'),
  ('Wataru Endo', 'Japón', 'MID', 'Liverpool'),
  ('Junya Ito', 'Japón', 'MID', 'Genk'),
  ('Daichi Kamada', 'Japón', 'MID', 'Crystal Palace'),
  ('Koki Ogawa', 'Japón', 'MID', 'NEC Nijmegen'),
  ('Daizen Maeda', 'Japón', 'MID', 'Celtic'),
  ('Ritsu Doan', 'Japón', 'MID', 'Eintracht Frankfurt'),
  ('Ao Tanaka', 'Japón', 'MID', 'Leeds United'),
  ('Kaishu Sano', 'Japón', 'MID', 'Mainz 05'),
  ('Takefusa Kubo', 'Japón', 'MID', 'Real Sociedad'),
  ('Ayase Ueda', 'Japón', 'FWD', 'Feyenoord'),
  ('Keito Nakamura', 'Japón', 'FWD', 'Stade de Reims'),
  ('Ito Suzuki', 'Japón', 'FWD', 'SC Freiburg'),
  ('Kento Shiode', 'Japón', 'FWD', 'Wolfsburg'),
  ('Keisuke Goto', 'Japón', 'FWD', 'Sint-Truiden'),
  ('Viktor Johansson', 'Suecia', 'GK', 'Stoke City'),
  ('Kristoffer Nordfeldt', 'Suecia', 'GK', 'AIK'),
  ('Jacob Widell Zetterstrom', 'Suecia', 'GK', 'Derby County'),
  ('Hjalmar Ekdal', 'Suecia', 'DEF', 'Burnley'),
  ('Gabriel Gudmundsson', 'Suecia', 'DEF', 'Leeds United'),
  ('Isak Hien', 'Suecia', 'DEF', 'Atalanta'),
  ('Emil Holm', 'Suecia', 'DEF', 'Juventus'),
  ('Gustaf Lagerbielke', 'Suecia', 'DEF', 'Braga'),
  ('Victor Lindelof', 'Suecia', 'DEF', 'Aston Villa'),
  ('Erik Smith', 'Suecia', 'DEF', 'St. Pauli'),
  ('Carl Starfelt', 'Suecia', 'DEF', 'Celta Vigo'),
  ('Elliot Stroud', 'Suecia', 'DEF', 'Mjallby'),
  ('Daniel Svensson', 'Suecia', 'DEF', 'Borussia Dortmund'),
  ('Taha Ali', 'Suecia', 'MID', 'Malmo'),
  ('Yasin Ayari', 'Suecia', 'MID', 'Brighton'),
  ('Lucas Bergvall', 'Suecia', 'MID', 'Tottenham'),
  ('Jesper Karlstrom', 'Suecia', 'MID', 'Udinese'),
  ('Ken Sema', 'Suecia', 'MID', 'Pafos'),
  ('Mattias Svanberg', 'Suecia', 'MID', 'Wolfsburg'),
  ('Besfort Zeneli', 'Suecia', 'MID', 'Union St-Gilloise'),
  ('Alexander Bernhardsson', 'Suecia', 'FWD', 'Holstein Kiel'),
  ('Anthony Elanga', 'Suecia', 'FWD', 'Newcastle United'),
  ('Viktor Gyokeres', 'Suecia', 'FWD', 'Arsenal'),
  ('Alexander Isak', 'Suecia', 'FWD', 'Liverpool'),
  ('Gustaf Nilsson', 'Suecia', 'FWD', 'Club Brugge'),
  ('Benjamin Nygren', 'Suecia', 'FWD', 'Celtic'),
  ('Sabri Ben Hessen', 'Túnez', 'GK', 'Etoile Sahel'),
  ('Abdelmouhib Chamakh', 'Túnez', 'GK', 'Club Africain'),
  ('Aymen Dahman', 'Túnez', 'GK', 'CS Sfaxien'),
  ('Ali Abdi', 'Túnez', 'DEF', 'Nice'),
  ('Adem Arous', 'Túnez', 'DEF', 'Kasimpasa'),
  ('Mohamed Amine Ben Hamida', 'Túnez', 'DEF', 'Esperance'),
  ('Dylan Bronn', 'Túnez', 'DEF', 'Servette Geneva'),
  ('Raed Chikhaoui', 'Túnez', 'DEF', 'US Monastir'),
  ('Moutaz Neffati', 'Túnez', 'DEF', 'Norrkoping'),
  ('Omar Rekik', 'Túnez', 'DEF', 'NK Maribor'),
  ('Montassar Talbi', 'Túnez', 'DEF', 'Lorient'),
  ('Yan Valery', 'Túnez', 'DEF', 'Young Boys Berne'),
  ('Mortadha Ben Ouanes', 'Túnez', 'MID', 'Kasimpasa'),
  ('Anis Ben Slimane', 'Túnez', 'MID', 'Norwich City'),
  ('Ismael Gharbi', 'Túnez', 'MID', 'Augsburg'),
  ('Rani Khedira', 'Túnez', 'MID', 'Union Berlin'),
  ('Mohamed Hadj Mahmoud', 'Túnez', 'MID', 'Lugano'),
  ('Hannibal Mejbri', 'Túnez', 'MID', 'Burnley'),
  ('Ellyes Skhiri', 'Túnez', 'MID', 'Eintracht Frankfurt'),
  ('Elias Achouri', 'Túnez', 'FWD', 'Copenhagen'),
  ('Khalil Ayari', 'Túnez', 'FWD', 'PSG'),
  ('Firas Chaouat', 'Túnez', 'FWD', 'Club Africain'),
  ('Rayan Elloumi', 'Túnez', 'FWD', 'Vancouver Whitecaps'),
  ('Hazem Mastouri', 'Túnez', 'FWD', 'Dynamo Makhachkala'),
  ('Elias Saad', 'Túnez', 'FWD', 'Hannover 96'),
  ('Sebastian Tounekti', 'Túnez', 'FWD', 'Celtic'),
  ('Thibaut Courtois', 'Bélgica', 'GK', 'Real Madrid'),
  ('Senne Lammens', 'Bélgica', 'GK', 'Manchester United'),
  ('Mike Penders', 'Bélgica', 'GK', 'Racing Strasbourg'),
  ('Timothy Castagne', 'Bélgica', 'DEF', 'Fulham'),
  ('Zeno Debast', 'Bélgica', 'DEF', 'Sporting Lisbon'),
  ('Maxim De Cuyper', 'Bélgica', 'DEF', 'Brighton & Hove Albion'),
  ('Koni De Winter', 'Bélgica', 'DEF', 'AC Milan'),
  ('Brandon Mechele', 'Bélgica', 'DEF', 'Club Brugge'),
  ('Thomas Meunier', 'Bélgica', 'DEF', 'Lille'),
  ('Nathan Ngoy', 'Bélgica', 'DEF', 'Lille'),
  ('Joaquin Seys', 'Bélgica', 'DEF', 'Club Brugge'),
  ('Arthur Theate', 'Bélgica', 'DEF', 'Eintracht Frankfurt'),
  ('Kevin De Bruyne', 'Bélgica', 'MID', 'Napoli'),
  ('Amadou Onana', 'Bélgica', 'MID', 'Aston Villa'),
  ('Nicolas Raskin', 'Bélgica', 'MID', 'Rangers'),
  ('Youri Tielemans', 'Bélgica', 'MID', 'Aston Villa'),
  ('Hans Vanaken', 'Bélgica', 'MID', 'Club Brugge'),
  ('Axel Witsel', 'Bélgica', 'MID', 'Girona'),
  ('Charles De Ketelaere', 'Bélgica', 'FWD', 'Atalanta'),
  ('Jeremy Doku', 'Bélgica', 'FWD', 'Manchester City'),
  ('Matias Fernandez-Pardo', 'Bélgica', 'FWD', 'Lille'),
  ('Romelu Lukaku', 'Bélgica', 'FWD', 'Napoli'),
  ('Dodi Lukebakio', 'Bélgica', 'FWD', 'Benfica'),
  ('Diego Moreira', 'Bélgica', 'FWD', 'Racing Strasbourg'),
  ('Alexis Saelemaekers', 'Bélgica', 'FWD', 'AC Milan'),
  ('Leandro Trossard', 'Bélgica', 'FWD', 'Arsenal'),
  ('Mohamed El Shenawy', 'Egipto', 'GK', 'Al Ahly'),
  ('Mostafa Shobeir', 'Egipto', 'GK', 'Al Ahly'),
  ('El Mahdi Soliman', 'Egipto', 'GK', 'Zamalek'),
  ('Mohamed Alaa', 'Egipto', 'GK', 'El Gouna'),
  ('Mohamed Hany', 'Egipto', 'DEF', 'Al Ahly'),
  ('Tarek Alaa', 'Egipto', 'DEF', 'Zed'),
  ('Hamdy Fathy', 'Egipto', 'DEF', 'Al Wakrah'),
  ('Rami Rabia', 'Egipto', 'DEF', 'Al Ain'),
  ('Yasser Ibrahim', 'Egipto', 'DEF', 'Al Ahly'),
  ('Hossam Abdelmaguid', 'Egipto', 'DEF', 'Zamalek'),
  ('Mohamed Abdelmonemn', 'Egipto', 'DEF', 'Nice'),
  ('Ahmed Fatouh', 'Egipto', 'DEF', 'Zamalek'),
  ('Karim Hafez', 'Egipto', 'DEF', 'Pyramids'),
  ('Marwan Ateya', 'Egipto', 'MID', 'Al Ahly'),
  ('Mohanad Lasheen', 'Egipto', 'MID', 'Pyramids'),
  ('Nabil Emad', 'Egipto', 'MID', 'Al Najma'),
  ('Mahmoud Saber', 'Egipto', 'MID', 'Zed'),
  ('Ahmed Zizo', 'Egipto', 'MID', 'Al Ahly'),
  ('Emam Ashour', 'Egipto', 'MID', 'Al Ahly'),
  ('Mostafa Ziko', 'Egipto', 'MID', 'Pyramids'),
  ('Mahmoud Trezeguet', 'Egipto', 'MID', 'Al Ahly'),
  ('Ibrahim Adel', 'Egipto', 'MID', 'Nordsjaelland'),
  ('Haissem Hassan', 'Egipto', 'MID', 'Real Ovideo'),
  ('Omar Marmoush', 'Egipto', 'FWD', 'Manchester City'),
  ('Mohamed Salah', 'Egipto', 'FWD', 'Liverpool'),
  ('Aqtay Abdallah', 'Egipto', 'FWD', 'Enppi'),
  ('Hamza Abdelkarim', 'Egipto', 'FWD', 'Barcelona'),
  ('Max Crocombe', 'Nueva Zelanda', 'GK', 'Millwall'),
  ('Alex Paulsen', 'Nueva Zelanda', 'GK', 'Lechia Gdańsk'),
  ('Michael Woud', 'Nueva Zelanda', 'GK', 'Auckland'),
  ('Tim Payne', 'Nueva Zelanda', 'DEF', 'Wellington Phoenix'),
  ('Francis De Vries', 'Nueva Zelanda', 'DEF', 'Auckland'),
  ('Tyler Bindon', 'Nueva Zelanda', 'DEF', 'Nottingham Forest'),
  ('Michael Boxall', 'Nueva Zelanda', 'DEF', 'Minnesota United'),
  ('Liberato Cacace', 'Nueva Zelanda', 'DEF', 'Wrexham'),
  ('Nando Pijnaker', 'Nueva Zelanda', 'DEF', 'Auckland FC'),
  ('Finn Surman', 'Nueva Zelanda', 'DEF', 'Portland Timbers'),
  ('Callan Elliot', 'Nueva Zelanda', 'DEF', 'Auckland'),
  ('Tommy Smith', 'Nueva Zelanda', 'DEF', 'Braintree Town'),
  ('Joe Bell', 'Nueva Zelanda', 'MID', 'Viking FK'),
  ('Matt Garbett', 'Nueva Zelanda', 'MID', 'Peterborough United'),
  ('Marko Stamenic', 'Nueva Zelanda', 'MID', 'Swansea City'),
  ('Sarpreet Singh', 'Nueva Zelanda', 'MID', 'Wellington Phoenix'),
  ('Alex Rufer', 'Nueva Zelanda', 'MID', 'Wellington Phoenix'),
  ('Ryan Thomas', 'Nueva Zelanda', 'MID', 'PEC Zwolle'),
  ('Chris Wood', 'Nueva Zelanda', 'FWD', 'Nottingham Forest'),
  ('Eli Just', 'Nueva Zelanda', 'FWD', 'Motherwell'),
  ('Kosta Barbarouses', 'Nueva Zelanda', 'FWD', 'Western Sydney Wanderers'),
  ('Ben Waine', 'Nueva Zelanda', 'FWD', 'Port Vale'),
  ('Ben Old', 'Nueva Zelanda', 'FWD', 'Saint-Étienne'),
  ('Callum McCowatt', 'Nueva Zelanda', 'FWD', 'Silkeborg IF'),
  ('Jesse Randall', 'Nueva Zelanda', 'FWD', 'Auckland FC'),
  ('Lachlan Bayliss', 'Nueva Zelanda', 'FWD', 'Newcastle Jets'),
  ('Unai Simon', 'España', 'GK', 'Athletic Club'),
  ('David Raya', 'España', 'GK', 'Arsenal'),
  ('Joan Garcia', 'España', 'GK', 'Barcelona'),
  ('Aymeric Laporte', 'España', 'DEF', 'Athletic Club'),
  ('Marc Cucurella', 'España', 'DEF', 'Chelsea'),
  ('Marcos Llorente', 'España', 'DEF', 'Atletico Madrid'),
  ('Eric Garcia', 'España', 'DEF', 'Barcelona'),
  ('Pedro Porro', 'España', 'DEF', 'Tottenham'),
  ('Alex Grimaldo', 'España', 'DEF', 'Bayer Leverkusen'),
  ('Pau Cubarsi', 'España', 'DEF', 'Barcelona'),
  ('Marc Pubill', 'España', 'DEF', 'Atletico Madrid'),
  ('Rodri', 'España', 'MID', 'Manchester City'),
  ('Fabian Ruiz', 'España', 'MID', 'Paris Saint-Germain'),
  ('Mikel Merino', 'España', 'MID', 'Arsenal'),
  ('Pedri', 'España', 'MID', 'Barcelona'),
  ('Gavi', 'España', 'MID', 'Barcelona'),
  ('Martin Zubimendi', 'España', 'MID', 'Arsenal'),
  ('Alex Baena', 'España', 'MID', 'Atletico Madrid'),
  ('Ferran Torres', 'España', 'FWD', 'Barcelona'),
  ('Mikel Oyarzabal', 'España', 'FWD', 'Real Sociedad'),
  ('Dani Olmo', 'España', 'FWD', 'Barcelona'),
  ('Nico Williams', 'España', 'FWD', 'Athletic Club'),
  ('Lamine Yamal', 'España', 'FWD', 'Barcelona'),
  ('Yeremy Pino', 'España', 'FWD', 'Crystal Palace'),
  ('Borja Iglesias', 'España', 'FWD', 'Celta Vigo'),
  ('Victor Munoz', 'España', 'FWD', 'Osasuna'),
  ('Vozinha', 'Cabo Verde', 'GK', 'Chaves'),
  ('Marcio Rosa', 'Cabo Verde', 'GK', 'Montana'),
  ('CJ dos Santos', 'Cabo Verde', 'GK', 'San Diego'),
  ('Stopira', 'Cabo Verde', 'DEF', 'Torreense'),
  ('Roberto Lopes', 'Cabo Verde', 'DEF', 'Shamrock Rovers'),
  ('Joao Paulo', 'Cabo Verde', 'DEF', 'FCSB'),
  ('Diney', 'Cabo Verde', 'DEF', 'Al Bataeh'),
  ('Logan Costa', 'Cabo Verde', 'DEF', 'Villarreal'),
  ('Steven Moreira', 'Cabo Verde', 'DEF', 'Columbus Crew'),
  ('Wagner Pina', 'Cabo Verde', 'DEF', 'Trabzonspor'),
  ('Sidny Lopes Cabral', 'Cabo Verde', 'DEF', 'Benfica'),
  ('Kelvin Pires', 'Cabo Verde', 'DEF', 'SJK'),
  ('Jamiro Monteiro', 'Cabo Verde', 'MID', 'PEC Zwolle'),
  ('Kevin Pina', 'Cabo Verde', 'MID', 'Krasnodar'),
  ('Deroy Duarte', 'Cabo Verde', 'MID', 'Ludogorets'),
  ('Telmo Arcanjo', 'Cabo Verde', 'MID', 'Vitoria Guimaraes'),
  ('Laros Duarte', 'Cabo Verde', 'MID', 'Puskas Akademia'),
  ('Yannick Semedo', 'Cabo Verde', 'MID', 'Farense'),
  ('Ryan Mendes', 'Cabo Verde', 'FWD', 'Igdir'),
  ('Garry Rodrigues', 'Cabo Verde', 'FWD', 'Apollon Limassol'),
  ('Willy Semedo', 'Cabo Verde', 'FWD', 'Omonia'),
  ('Jovane Cabral', 'Cabo Verde', 'FWD', 'Estrela Amadora'),
  ('Gilson Tavares', 'Cabo Verde', 'FWD', 'Akron Tolyatti'),
  ('Dailon Livramento', 'Cabo Verde', 'FWD', 'Casa Pia'),
  ('Helio Varela', 'Cabo Verde', 'FWD', 'Maccabi Tel Aviv'),
  ('Nuno da Costa', 'Cabo Verde', 'FWD', 'Istanbul Basaksehir'),
  ('Mike Maignan', 'Francia', 'GK', 'AC Milan'),
  ('Robin Risser', 'Francia', 'GK', 'Lens'),
  ('Brice Samba', 'Francia', 'GK', 'Rennes'),
  ('Lucas Digne', 'Francia', 'DEF', 'Aston Villa'),
  ('Malo Gusto', 'Francia', 'DEF', 'Chelsea'),
  ('Lucas Hernández', 'Francia', 'DEF', 'Paris Saint-Germain'),
  ('Theo Hernández', 'Francia', 'DEF', 'Al Hilal'),
  ('Ibrahima Konaté', 'Francia', 'DEF', 'Liverpool'),
  ('Jules Koundé', 'Francia', 'DEF', 'Barcelona'),
  ('Maxence Lacroix', 'Francia', 'DEF', 'Crystal Palace'),
  ('William Saliba', 'Francia', 'DEF', 'Arsenal'),
  ('Dayot Upamecano', 'Francia', 'DEF', 'Bayern Munich'),
  ('N''Golo Kanté', 'Francia', 'MID', 'Fenerbahçe'),
  ('Manu Koné', 'Francia', 'MID', 'AS Roma'),
  ('Adrien Rabiot', 'Francia', 'MID', 'AC Milan'),
  ('Aurélien Tchouaméni', 'Francia', 'MID', 'Real Madrid'),
  ('Warren Zaïre-Emery', 'Francia', 'MID', 'Paris Saint-Germain'),
  ('Maghnes Akliouche', 'Francia', 'FWD', 'AS Monaco'),
  ('Bradley Barcola', 'Francia', 'FWD', 'Paris Saint-Germain'),
  ('Rayan Cherki', 'Francia', 'FWD', 'Manchester City'),
  ('Ousmane Dembélé', 'Francia', 'FWD', 'Paris Saint-Germain'),
  ('Désiré Doué', 'Francia', 'FWD', 'Paris Saint-Germain'),
  ('Jean-Philippe Mateta', 'Francia', 'FWD', 'Crystal Palace'),
  ('Kylian Mbappé', 'Francia', 'FWD', 'Real Madrid'),
  ('Michael Olise', 'Francia', 'FWD', 'Bayern Munich'),
  ('Marcus Thuram', 'Francia', 'FWD', 'Inter Milan'),
  ('Édouard Mendy', 'Senegal', 'GK', 'Al-Ahli'),
  ('Mory Diaw', 'Senegal', 'GK', 'Le Havre AC'),
  ('Yehvann Diouf', 'Senegal', 'GK', 'OGC Nice'),
  ('Krépin Diatta', 'Senegal', 'DEF', 'AS Monaco'),
  ('Antoine Mendy', 'Senegal', 'DEF', 'OGC Nice'),
  ('Kalidou Koulibaly', 'Senegal', 'DEF', 'Al-Hilal'),
  ('El Hadji Malick Diouf', 'Senegal', 'DEF', 'West Ham United'),
  ('Mamadou Sarr', 'Senegal', 'DEF', 'Chelsea'),
  ('Moussa Niakhaté', 'Senegal', 'DEF', 'Lyon'),
  ('Moustapha Mbow', 'Senegal', 'DEF', 'Paris FC'),
  ('Abdoulaye Seck', 'Senegal', 'DEF', 'Maccabi Haifa'),
  ('Ismaïl Jakobs', 'Senegal', 'DEF', 'Galatasaray SK'),
  ('Ilay Camara', 'Senegal', 'DEF', 'Anderlecht'),
  ('Idrissa Gana Gueye', 'Senegal', 'MID', 'Everton'),
  ('Pape Gueye', 'Senegal', 'MID', 'Villarreal CF'),
  ('Lamine Camara', 'Senegal', 'MID', 'AS Monaco'),
  ('Habib Diarra', 'Senegal', 'MID', 'Sunderland'),
  ('Pathé Ciss', 'Senegal', 'MID', 'Rayo Vallecano'),
  ('Pape Matar Sarr', 'Senegal', 'MID', 'Tottenham Hotspur'),
  ('Bara Sapoko Ndiaye', 'Senegal', 'MID', 'Bayern Munich'),
  ('Sadio Mané', 'Senegal', 'FWD', 'Al-Nassr'),
  ('Ismaïla Sarr', 'Senegal', 'FWD', 'Crystal Palace'),
  ('Iliman Ndiaye', 'Senegal', 'FWD', 'Everton'),
  ('Assane Diao', 'Senegal', 'FWD', 'Como'),
  ('Ibrahim Mbaye', 'Senegal', 'FWD', 'PSG'),
  ('Nicolas Jackson', 'Senegal', 'FWD', 'Chelsea'),
  ('Bamba Dieng', 'Senegal', 'FWD', 'Lorient'),
  ('Chérif Ndiaye', 'Senegal', 'FWD', 'Samsunspor'),
  ('Orjan Haskjold Nyland', 'Noruega', 'GK', 'Sevilla'),
  ('Egil Selvik', 'Noruega', 'GK', 'Watford'),
  ('Sander Tangvik', 'Noruega', 'GK', 'Hamburger SV'),
  ('Julian Ryerson', 'Noruega', 'DEF', 'Borussia Dortmund'),
  ('Marcus Holmgren Pedersen', 'Noruega', 'DEF', 'Torino'),
  ('David Moller Wolfe', 'Noruega', 'DEF', 'Wolverhampton'),
  ('Fredrik Bjorkan', 'Noruega', 'DEF', 'Bodo/Glimt'),
  ('Kristoffer Ajer', 'Noruega', 'DEF', 'Brentford'),
  ('Torbjorn Heggem', 'Noruega', 'DEF', 'Bologna'),
  ('Leo Skiri Ostigard', 'Noruega', 'DEF', 'Genoa'),
  ('Sondre Langas', 'Noruega', 'DEF', 'Derby County'),
  ('Henrik Falchener', 'Noruega', 'DEF', 'Viking'),
  ('Martin Odegaard', 'Noruega', 'MID', 'Arsenal'),
  ('Sander Berge', 'Noruega', 'MID', 'Fulham'),
  ('Fredrik Aursnes', 'Noruega', 'MID', 'Benfica'),
  ('Patrick Berg', 'Noruega', 'MID', 'Bodo/Glimt'),
  ('Kristian Thorstvedt', 'Noruega', 'MID', 'Sassuolo'),
  ('Morten Thorsby', 'Noruega', 'MID', 'Cremonese'),
  ('Thelo Aasgaard', 'Noruega', 'MID', 'Rangers'),
  ('Erling Haaland', 'Noruega', 'FWD', 'Manchester City'),
  ('Alexander Sorloth', 'Noruega', 'FWD', 'Atletico Madrid'),
  ('Jorgen Strand Larsen', 'Noruega', 'FWD', 'Crystal Palace'),
  ('Antonio Nusa', 'Noruega', 'FWD', 'RB Leipzig'),
  ('Oscar Bobb', 'Noruega', 'FWD', 'Fulham'),
  ('Andreas Schjelderup', 'Noruega', 'FWD', 'Benfica'),
  ('Jens Petter Hauge', 'Noruega', 'FWD', 'Bodo/Glimt'),
  ('Emiliano Martínez', 'Argentina', 'GK', 'Aston Villa'),
  ('Juan Musso', 'Argentina', 'GK', 'Atletico Madrid'),
  ('Geronimo Rulli', 'Argentina', 'GK', 'Olympique de Marseille'),
  ('Leonardo Balerdi', 'Argentina', 'DEF', 'Marseille'),
  ('Lisandro Martínez', 'Argentina', 'DEF', 'Manchester United'),
  ('Facundo Medina', 'Argentina', 'DEF', 'Marseille'),
  ('Nahuel Molina', 'Argentina', 'DEF', 'Atletico Madrid'),
  ('Gonzalo Montiel', 'Argentina', 'DEF', 'River Plate'),
  ('Nicolas Otamendi', 'Argentina', 'DEF', 'Benfica'),
  ('Cristian Romero', 'Argentina', 'DEF', 'Tottenham'),
  ('Nicolas Tagliafico', 'Argentina', 'DEF', 'Lyon'),
  ('Valentín Barco', 'Argentina', 'MID', 'Strasbourg'),
  ('Rodrigo De Paul', 'Argentina', 'MID', 'Inter Miami'),
  ('Enzo Fernandez', 'Argentina', 'MID', 'Chelsea'),
  ('Giovani Lo Celso', 'Argentina', 'MID', 'Real Betis'),
  ('Alexis Mac Allister', 'Argentina', 'MID', 'Liverpool'),
  ('Exequiel Palacios', 'Argentina', 'MID', 'Bayer Leverkusen'),
  ('Leandro Paredes', 'Argentina', 'MID', 'Boca Juniors'),
  ('Thiago Almada', 'Argentina', 'FWD', 'Atletico Madrid'),
  ('Julian Alvarez', 'Argentina', 'FWD', 'Atletico Madrid'),
  ('Nicolas Gonzalez', 'Argentina', 'FWD', 'Atletico Madrid'),
  ('Jose Manuel Lopez', 'Argentina', 'FWD', 'Palmeiras'),
  ('Lautaro Martínez', 'Argentina', 'FWD', 'Inter Milan'),
  ('Lionel Messi', 'Argentina', 'FWD', 'Inter Miami'),
  ('Nicolas Paz', 'Argentina', 'FWD', 'Como'),
  ('Giuliano Simeone', 'Argentina', 'FWD', 'Atletico Madrid'),
  ('Alexander Schlager', 'Austria', 'GK', 'Red Bull Salzburg'),
  ('Florian Wiegele', 'Austria', 'GK', 'Viktoria Plzen'),
  ('Patrick Pentz', 'Austria', 'GK', 'Brondby'),
  ('David Affengruber', 'Austria', 'DEF', 'Elche'),
  ('Kevin Danso', 'Austria', 'DEF', 'Tottenham'),
  ('Stefan Posch', 'Austria', 'DEF', 'Como'),
  ('David Alaba', 'Austria', 'DEF', 'Real Madrid'),
  ('Philipp Lienhart', 'Austria', 'DEF', 'Freiburg'),
  ('Phillipp Mwene', 'Austria', 'DEF', 'Mainz'),
  ('Alexander Prass', 'Austria', 'DEF', 'Hoffenheim'),
  ('Marco Friedl', 'Austria', 'DEF', 'Werder Bremen'),
  ('Michael Svoboda', 'Austria', 'DEF', 'Venezia'),
  ('Xaver Schlager', 'Austria', 'MID', 'RB Leipzig'),
  ('Nicolas Seiwald', 'Austria', 'MID', 'RB Leipzig'),
  ('Marcel Sabitzer', 'Austria', 'MID', 'Borussia Dortmund'),
  ('Florian Grillitsch', 'Austria', 'MID', 'Braga'),
  ('Carney Chukwuemeka', 'Austria', 'MID', 'Borussia Dortmund'),
  ('Romano Schmid', 'Austria', 'MID', 'Werder Bremen'),
  ('Christoph Baumgartner', 'Austria', 'MID', 'Hoffenheim'),
  ('Konrad Laimer', 'Austria', 'MID', 'Bayern Munich'),
  ('Patrick Wimmer', 'Austria', 'MID', 'VfL Wolfsburg'),
  ('Paul Wanner', 'Austria', 'MID', 'PSV'),
  ('Alessandro Schopf', 'Austria', 'MID', 'Wolfsberger'),
  ('Marko Arnautovic', 'Austria', 'FWD', 'Red Star Belgrade'),
  ('Michael Gregoritsch', 'Austria', 'FWD', 'Brondby'),
  ('Sasa Kalajdzic', 'Austria', 'FWD', 'Wolves'),
  ('Diogo Costa', 'Portugal', 'GK', 'FC Porto'),
  ('José Sá', 'Portugal', 'GK', 'Wolverhampton Wanderers'),
  ('Rui Silva', 'Portugal', 'GK', 'Sporting CP'),
  ('Ricardo Velho', 'Portugal', 'GK', 'Genclerbirligi Ankara'),
  ('Diogo Dalot', 'Portugal', 'DEF', 'Manchester United'),
  ('Matheus Nunes', 'Portugal', 'DEF', 'Manchester City'),
  ('Nélson Semedo', 'Portugal', 'DEF', 'Fenerbahçe SK'),
  ('João Cancelo', 'Portugal', 'DEF', 'FC Barcelona'),
  ('Nuno Mendes', 'Portugal', 'DEF', 'PSG'),
  ('Gonçalo Inácio', 'Portugal', 'DEF', 'Sporting CP'),
  ('Renato Veiga', 'Portugal', 'DEF', 'Villarreal'),
  ('Rúben Dias', 'Portugal', 'DEF', 'Manchester City'),
  ('Tomás Araújo', 'Portugal', 'DEF', 'SL Benfica'),
  ('Rúben Neves', 'Portugal', 'MID', 'Al Hilal'),
  ('Samuel Costa', 'Portugal', 'MID', 'Mallorca'),
  ('João Neves', 'Portugal', 'MID', 'PSG'),
  ('Vitinha', 'Portugal', 'MID', 'PSG'),
  ('Bruno Fernandes', 'Portugal', 'MID', 'Manchester United'),
  ('Bernardo Silva', 'Portugal', 'MID', 'Manchester City'),
  ('João Félix', 'Portugal', 'FWD', 'Al Nassr'),
  ('Francisco Trincão', 'Portugal', 'FWD', 'Sporting CP'),
  ('Francisco Conceição', 'Portugal', 'FWD', 'Juventus'),
  ('Pedro Neto', 'Portugal', 'FWD', 'Chelsea'),
  ('Rafael Leão', 'Portugal', 'FWD', 'AC Milan'),
  ('Gonçalo Guedes', 'Portugal', 'FWD', 'Real Sociedad'),
  ('Gonçalo Ramos', 'Portugal', 'FWD', 'PSG'),
  ('Cristiano Ronaldo', 'Portugal', 'FWD', 'Al Nassr'),
  ('Matthieu Epolo', 'República Democrática del Congo', 'GK', 'Standard Liege'),
  ('Timothy Fayulu', 'República Democrática del Congo', 'GK', 'Noah'),
  ('Lionel Mpasi', 'República Democrática del Congo', 'GK', 'Le Havre'),
  ('Dylan Batubinsika', 'República Democrática del Congo', 'DEF', 'Larisa'),
  ('Rocky Bushiri', 'República Democrática del Congo', 'DEF', 'Hibernian'),
  ('Gedeon Kalulu', 'República Democrática del Congo', 'DEF', 'Aris Limassol'),
  ('Steve Kapuadi', 'República Democrática del Congo', 'DEF', 'Widzew Lodz'),
  ('Joris Kayembe', 'República Democrática del Congo', 'DEF', 'Racing Genk'),
  ('Arthur Masuaku', 'República Democrática del Congo', 'DEF', 'Racing Lens'),
  ('Chancel Mbemba', 'República Democrática del Congo', 'DEF', 'Lille'),
  ('Axel Tuanzebe', 'República Democrática del Congo', 'DEF', 'Burnley'),
  ('Aaron Wan-Bissaka', 'República Democrática del Congo', 'DEF', 'West Ham'),
  ('Theo Bongonda', 'República Democrática del Congo', 'MID', 'Spartak Moscow'),
  ('Brian Cipenga', 'República Democrática del Congo', 'MID', 'Castellon'),
  ('Meshack Elia', 'República Democrática del Congo', 'MID', 'Alanyaspor'),
  ('Gael Kakuta', 'República Democrática del Congo', 'MID', 'Larisa'),
  ('Edo Kayembe', 'República Democrática del Congo', 'MID', 'Watford'),
  ('Nathanael Mbuku', 'República Democrática del Congo', 'MID', 'Montpellier'),
  ('Samuel Moutoussamy', 'República Democrática del Congo', 'MID', 'Atromitos'),
  ('Ngal''ayel Mukau', 'República Democrática del Congo', 'MID', 'Lille'),
  ('Charles Pickel', 'República Democrática del Congo', 'MID', 'Espanyol'),
  ('Noah Sadiki', 'República Democrática del Congo', 'MID', 'Sunderland'),
  ('Cedric Bakambu', 'República Democrática del Congo', 'FWD', 'Real Betis'),
  ('Simon Banza', 'República Democrática del Congo', 'FWD', 'Al Jazira'),
  ('Fiston Mayele', 'República Democrática del Congo', 'FWD', 'Pyramids'),
  ('Yoane Wissa', 'República Democrática del Congo', 'FWD', 'Newcastle'),
  ('Camilo Vargas', 'Colombia', 'GK', 'Atlas'),
  ('Alvaro Montero', 'Colombia', 'GK', 'Velez Sarsfield'),
  ('David Ospina', 'Colombia', 'GK', 'Atletico Nacional'),
  ('Davinson Sanchez', 'Colombia', 'DEF', 'Galatasaray'),
  ('Jhon Lucumi', 'Colombia', 'DEF', 'Bologna'),
  ('Yerry Mina', 'Colombia', 'DEF', 'Cagliari'),
  ('Willer Ditta', 'Colombia', 'DEF', 'Cruz Azul'),
  ('Daniel Munoz', 'Colombia', 'DEF', 'Crystal Palace'),
  ('Santiago Arias', 'Colombia', 'DEF', 'Independiente'),
  ('Johan Mojica', 'Colombia', 'DEF', 'Mallorca'),
  ('Deiver Machado', 'Colombia', 'DEF', 'Nantes'),
  ('Richard Rios', 'Colombia', 'MID', 'Benfica'),
  ('Jefferson Lerma', 'Colombia', 'MID', 'Crystal Palace'),
  ('Kevin Castano', 'Colombia', 'MID', 'River Plate'),
  ('Juan Camilo Portilla', 'Colombia', 'MID', 'Athletico Paranaense'),
  ('Gustavo Puerta', 'Colombia', 'MID', 'Racing de Santander'),
  ('Jhon Arias', 'Colombia', 'MID', 'Palmeiras'),
  ('Jorge Carrascal', 'Colombia', 'MID', 'Flamengo'),
  ('Juan Fernando Quintero', 'Colombia', 'MID', 'River Plate'),
  ('James Rodriguez', 'Colombia', 'MID', 'Minnesota United'),
  ('Jaminton Campaz', 'Colombia', 'MID', 'Rosario Central'),
  ('Juan Camilo Hernandez', 'Colombia', 'FWD', 'Real Betis'),
  ('Luis Diaz', 'Colombia', 'FWD', 'Bayern Munich'),
  ('Luis Suarez', 'Colombia', 'FWD', 'Sporting CP'),
  ('Carlos Andres Gomez', 'Colombia', 'FWD', 'Vasco da Gama'),
  ('Jhon Cordoba', 'Colombia', 'FWD', 'FC Krasnodar'),
  ('Jordan Pickford', 'Inglaterra', 'GK', 'Everton'),
  ('Dean Henderson', 'Inglaterra', 'GK', 'Crystal Palace'),
  ('James Trafford', 'Inglaterra', 'GK', 'Manchester City'),
  ('Reece James', 'Inglaterra', 'DEF', 'Chelsea'),
  ('Ezri Konsa', 'Inglaterra', 'DEF', 'Aston Villa'),
  ('Jarell Quansah', 'Inglaterra', 'DEF', 'Bayer Leverkusen'),
  ('John Stones', 'Inglaterra', 'DEF', 'Manchester City'),
  ('Marc Guehi', 'Inglaterra', 'DEF', 'Manchester City'),
  ('Dan Burn', 'Inglaterra', 'DEF', 'Newcastle'),
  ('Nico O''Reilly', 'Inglaterra', 'DEF', 'Manchester City'),
  ('Djed Spence', 'Inglaterra', 'DEF', 'Tottenham'),
  ('Tino Livramento', 'Inglaterra', 'DEF', 'Newcastle'),
  ('Declan Rice', 'Inglaterra', 'MID', 'Arsenal'),
  ('Elliot Anderson', 'Inglaterra', 'MID', 'Nottingham Forest'),
  ('Kobbie Mainoo', 'Inglaterra', 'MID', 'Manchester United'),
  ('Jordan Henderson', 'Inglaterra', 'MID', 'Brentford'),
  ('Morgan Rogers', 'Inglaterra', 'MID', 'Aston Villa'),
  ('Jude Bellingham', 'Inglaterra', 'MID', 'Real Madrid'),
  ('Eberechi Eze', 'Inglaterra', 'MID', 'Arsenal'),
  ('Harry Kane', 'Inglaterra', 'FWD', 'Bayern Munich'),
  ('Ivan Toney', 'Inglaterra', 'FWD', 'Al Ahli'),
  ('Ollie Watkins', 'Inglaterra', 'FWD', 'Aston Villa'),
  ('Bukayo Saka', 'Inglaterra', 'FWD', 'Arsenal'),
  ('Marcus Rashford', 'Inglaterra', 'FWD', 'Barcelona'),
  ('Anthony Gordon', 'Inglaterra', 'FWD', 'Newcastle'),
  ('Noni Madueke', 'Inglaterra', 'FWD', 'Arsenal'),
  ('Dominik Livakovic', 'Croacia', 'GK', 'Dinamo Zagreb'),
  ('Dominik Kotarski', 'Croacia', 'GK', 'Copenhagen'),
  ('Ivor Pandur', 'Croacia', 'GK', 'Hull'),
  ('Josko Gvardiol', 'Croacia', 'DEF', 'Man City'),
  ('Duje Caleta-Car', 'Croacia', 'DEF', 'Real Sociedad'),
  ('Josip Sutalo', 'Croacia', 'DEF', 'Ajax'),
  ('Josip Stanisic', 'Croacia', 'DEF', 'Bayern Munich'),
  ('Marin Pongracic', 'Croacia', 'DEF', 'Fiorentina'),
  ('Martin Erlic', 'Croacia', 'DEF', 'Midtjylland'),
  ('Luka Vuskovic', 'Croacia', 'DEF', 'Hamburg'),
  ('Luka Modric', 'Croacia', 'MID', 'AC Milan'),
  ('Mateo Kovacic', 'Croacia', 'MID', 'Man City'),
  ('Mario Pasalic', 'Croacia', 'MID', 'Atalanta'),
  ('Nikola Vlasic', 'Croacia', 'MID', 'Torino'),
  ('Luka Sucic', 'Croacia', 'MID', 'Real Sociedad'),
  ('Martin Baturina', 'Croacia', 'MID', 'Como'),
  ('Kristijan Jakic', 'Croacia', 'MID', 'Augsburg'),
  ('Petar Sucic', 'Croacia', 'MID', 'Inter Milan'),
  ('Nikola Moro', 'Croacia', 'MID', 'Bologna'),
  ('Toni Fruk', 'Croacia', 'MID', 'Rijeka'),
  ('Ivan Perisic', 'Croacia', 'FWD', 'PSV Eindhoven'),
  ('Andrej Kramaric', 'Croacia', 'FWD', 'Hoffenheim'),
  ('Ante Budimir', 'Croacia', 'FWD', 'Osasuna'),
  ('Marco Pasalic', 'Croacia', 'FWD', 'Orlando City'),
  ('Petar Musa', 'Croacia', 'FWD', 'Dallas'),
  ('Igor Matanovic', 'Croacia', 'FWD', 'Freiburg'),
  ('Orlando Mosquera', 'Panamá', 'GK', 'Al-Fayha FC'),
  ('Luis Mejía', 'Panamá', 'GK', 'Club Nacional'),
  ('César Samudio', 'Panamá', 'GK', 'CD Marathón'),
  ('César Blackman', 'Panamá', 'DEF', 'Slovan Bratislava'),
  ('Jorge Gutiérrez', 'Panamá', 'DEF', 'Deportivo La Guaira'),
  ('Michael Amir Murillo', 'Panamá', 'DEF', 'Beşiktaş'),
  ('Fidel Escobar', 'Panamá', 'DEF', 'Saprissa'),
  ('Andrés Andrade', 'Panamá', 'DEF', 'LASK'),
  ('Edgardo Fariña', 'Panamá', 'DEF', 'Pari Nizhniy Novgorod'),
  ('José Córdoba', 'Panamá', 'DEF', 'Norwich City'),
  ('Éric Davis', 'Panamá', 'DEF', 'CD Plaza Amador'),
  ('Jiovany Ramos', 'Panamá', 'DEF', 'Academia Puerto Cabello'),
  ('Roderick Miller', 'Panamá', 'DEF', 'Turan Tovuz'),
  ('Aníbal Godoy', 'Panamá', 'MID', 'San Diego FC'),
  ('Adalberto Carrasquilla', 'Panamá', 'MID', 'Pumas UNAM'),
  ('Carlos Harvey', 'Panamá', 'MID', 'Minnesota United'),
  ('Cristian Martínez', 'Panamá', 'MID', 'Ironi Kiryat Shmona'),
  ('José Luis Rodríguez', 'Panamá', 'MID', 'FC Juárez'),
  ('César Yanis', 'Panamá', 'MID', 'Cobresal'),
  ('Yoel Bárcenas', 'Panamá', 'MID', 'Mazatlán FC'),
  ('Alberto Quintero', 'Panamá', 'MID', 'CD Plaza Amador'),
  ('Azarías Londoño', 'Panamá', 'MID', 'Universidad Católica de Chile'),
  ('Ismael Díaz', 'Panamá', 'FWD', 'Club León'),
  ('Cecilio Waterman', 'Panamá', 'FWD', 'Universidad de Concepción'),
  ('José Fajardo', 'Panamá', 'FWD', 'Universidad Católica'),
  ('Tomás Rodríguez', 'Panamá', 'FWD', 'Saprissa')
) as v(full_name, team, pos, club)
join public.national_teams t on t.name = v.team
where not exists (
  select 1 from public.players p
  where p.full_name = v.full_name and p.national_team_id = t.id
);
